version: '3'

services:
  app:
    image: portainer/agent:2.19.4
    container_name: portainer_agent
    restart: "unless-stopped"
    networks:
      - default
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

networks:
  default:
    name: portainer_agent
    driver: bridge
    enable_ipv6: false

